import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

describe("simulation export SKILL contract", () => {
	it("uses Cadence-native netlist and OCEAN export APIs without running simulation", async () => {
		const path = fileURLToPath(new URL("../../skill-runtime/simulation-export.il", import.meta.url));
		const source = await readFile(path, "utf8");

		expect(source).toContain("createNetlist(?recreateAll t ?display nil)");
		expect(source).toContain('?application "Assembler"');
		expect(source).toContain("axlWriteOceanScriptLCV");
		expect(source).toContain('topOceanPath = strcat(bundleDir "/maestro/maestro.ocn")');
		expect(source).toContain('sweepPath = strcat(testDir "/sweep.ocn")');
		expect(source).toContain("vaSimulationExportWriteSingleOceanScript(singlePath testSession)");
		expect(source).toContain("vaSimulationExportWriteTestSweepOceanScript(");
		expect(source).toContain("maeEnableTests(?all t ?enable nil ?session session)");
		expect(source).toContain("maeEnableTests(?testNames list(testName) ?enable t ?session session)");
		expect(source).toContain("vaSimulationExportRestoreEnabledTests(session enabledTests)");
		expect(source).toContain('member(scope list("none" "all" "top" "tests" "test"))');
		expect(source).toContain('(scope == "test" || (scope == "none" && requestedTestName != ""))');
		expect(source).toContain('exportTest = includeTests && (scope != "test" || testName == requestedTestName)');
		expect(source).toContain("procedure(vaSessionPrepareMaestroExportV7");
		expect(source).toContain('member(outputsMode list("none" "definitions" "results" "all"))');
		expect(source).toContain("axlOutputsExportToFile(session outputDefinitionsPath)");
		expect(source).toContain("historyEntry = axlGetCurrentHistory(session)");
		expect(source).toContain("historyData = axlGetHistory(setupDatabase)");
		expect(source).toContain("outputResultsHistoryName = nth(length(historyNames) - 1 historyNames)");
		expect(source).toContain("historyEntry = axlGetHistoryEntry(setupDatabase requestedHistoryName)");
		expect(source).toContain("outputResultsHistoryName = axlGetHistoryName(historyEntry)");
		expect(source).toContain("outputResultsResult = maeExportOutputView(");
		expect(source).toContain('?view "Detail"');
		expect(source).toContain('outputDefinitionsPath = strcat(bundleDir "/outputs/definitions/all.csv")');
		expect(source).toContain('outputResultsPath = strcat(bundleDir "/outputs/results/.all.csv")');
		expect(source).toContain('member(schematicInstancesMode list("none" "top-level"))');
		expect(source).toContain('schematicInstancesPath = strcat(bundleDir "/schematics/all.json")');
		expect(source).toContain("instances = cellView~>instances");
		expect(source).toContain("instance~>xy");
		expect(source).toContain("instance~>orient");
		expect(source).toContain("instance~>bBox");
		expect(source).toContain('"hierarchyPolicy\\":\\"top-level-only');
		expect(source).not.toContain("instance~>master~>instances");
		expect(source).toContain("procedure(vaSessionExportSchematicInstances");
		expect(source).toContain("existingSessions = maeGetSessions()");
		expect(source).toContain("maeGetTestSession");
		expect(source).toContain("asiGetDesignLibName(testSession)");
		expect(source).toContain("asiGetDesignCellName(testSession)");
		expect(source).toContain("asiGetDesignViewName(testSession)");
		expect(source).toContain("netlistResult = asiNetlist(testSession)");
		expect(source).toContain("netlistDir = asiGetNetlistDir(testSession)");
		expect(source).toContain("simInputFile = asiGetSimInputFileName(testSession)");
		expect(source).toContain("when(closeSession");
		expect(source).not.toContain("?noRun");
		expect(source).not.toContain("vaSessionCreateNetlistFromOcean");
		expect(source).not.toMatch(/^\s*run\(\)/m);
	});
});
